### ISSUE TITLE
Bug in mode selection menu (line 24)

### ISSUE THREAD

**Issue by wwakabobik** [elliot-labs/ARF-Converter#8]
It's is in contradiction with expected input (numbers instead of letters).

It should be:

set /p mmenu=Press A for Advanced, E for Easy and O for Options. Then press enter:
if %mmenu%==E set fromm=easy
if %mmenu%==E goto easy
if %mmenu%==A set fromm=advanced
if %mmenu%==A goto filetype
if %mmenu%==O set fromm=options
if %mmenu%==O goto options

**Comment by elliot-labs** [comment]
Thanks for the info! I will get to it!

**Comment by elliot-labs** [comment]
This no longer applies to the current version. Thanks for your interest!
The configurable bat version has been retired in favor of a fully featured Python version and easy-to-use batch versions.
