### ISSUE TITLE
Not working with native encoding during (wrong cfg created)

### ISSUE THREAD

**Issue by wwakabobik** [elliot-labs/ARF-Converter#9]
In case when path or filename contains native characters, wrong path/filelame will be written to cfg file (unreadable). 

It's because of encoding problem. For russian case I need to add following:
at start of the file:

title 1 
chcp 1251 > nul 

I think your script should be more flexible to handle any active encoding.

**Comment by elliot-labs** [comment]
The current version is broken (I am aware of it) I was sidetracked while I was developing it. I am going to fix it and create a Python port in addition to shell.

**Comment by elliot-labs** [comment]
This no longer applies to the current version. Thanks for your interest!
